### ISSUE TITLE
Usage of ter:token:refresh is not clear

### ISSUE THREAD

**Issue by gilbertsoft** [TYPO3/tailor#37]
I've tried to write a GH workflow to periodically refresh the access token and update the secrets. Currently it looks like user name and password are required for this action, I'm currently getting the error `No authentication credentials are defined.`

Wondering why I have to provide the credentials at all, thought for this reason the refresh token is provided. Saving the credentials at GH is a no go for some people.

**Comment by gilbertsoft** [comment]
This is my current draft (not finished):

```
name: Refresh TYPO3 API Tokens

on:
  schedule:
    - cron: '0 1 1 * *'

jobs:
  refresh-tokens:
    name: Refresh TYPO3 API Tokens
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, mbstring, json, zip, curl
          tools: composer:2

      - name: Install Tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Get new tokens
        id: tokens
        run: |
          composer exec tailor ter:token:refresh ${{ secrets.TYPO3_API_REFRESH_TOKEN }}
          echo ::set-output name=access_token::${}
          echo ::set-output name=refresh_token::${}

      - name: Update refresh token
        uses: hmanzur/actions-set-secret@v2
        with:
          name: TYPO3_API_REFRESH_TOKEN
          value: ${{ steps.tokens.outputs.refresh_token }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update access token
        uses: hmanzur/actions-set-secret@v2
        with:
          name: TYPO3_API_ACCESS_TOKEN
          value: ${{ steps.tokens.outputs.access_token }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
