### ISSUE TITLE
[FEATURE] I want to be able to tag my version with a v-prefix

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/tailor#8]
## Summary / Description

I'm tagging my extensions with `v1.0.0` with a v-prefix. I'm not sure if I should strip the v before or if the release command should internally remove it.

## Describe the solution you'd like

Remove the v-prefix either in the CI with some bash commands or internally.

**Comment by o-ba** [comment]
Hi @simonschaufi,

thanks for your time to open this issue. I think this however does not relate to tailor in the first place since tailor is just a cli client for the new REST API which requires the version in the `\d{1,3}\.\d{1,3}\.\d{1,3}` format. This is a specification from TER and is also documented here: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/DeclarationFile/Index.html.

Therefore, I think it's the correct behaviour that tailor only accepts this format as version number. Otherwise we had to handle an undefined amount of custom formats, which will surely become very complex in the long term. It's in my opinion the users task to provide the version to tailor in the required format, e.g. in a Github workflow. Tailor does not provide such workflow built-in, but only a basic example in the readme. The idea is that developers can just take this basic workflow example and adjust it to their personal needs, e.g. when using another tag format.

So my proposal is to copy the example workflow and to extend it for handling the leading `v`. This could be done by adjusting the pattern in the `Check tag` step and then removing the `v` in the `Get Version` step to receive a valid version number.

**Comment by simonschaufi** [comment]
I wanted to start a brainstorming what would be a good solution for this as I would call it standard to prefix git tags with `v` but with the suggested github actions template it doesn't work. This issue is either a task to add another documentation for removing the prefix with some bash command or do that within the command. I agree with removing the `v` before but need some help in how to do that as neither bash nor the github actions syntax is my strength.

**Comment by o-ba** [comment]
Hi, since there are actually some repositories using `v` as perfix, I agree we should mention that in the readme. Not in a new example, because the adjustments to be made to the existing example are quite sparse, but with a new `Note:` section.

Could you therefore please check if following adjustments work for you:

Before:

```yaml
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      - name: Get version
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
```

After:

```yaml
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      - name: Get version
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
```

If this does not work. Please share a link to the corresponding workflow so I can have a look at it.
